---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apple-health-db
  namespace: apple-health
spec:
  encryptedData:
    APPLE_HEALTH_DB_PASSWORD: AgC/85W0tbeY7fOwMBYb92+mDHEV5hrRjC8r05b1G+2G87pj2GPU038RINEk/L/XkgFoqb0yceOZjO7M4NMGEog80GPHwrPfBO7TRbjfPpTMilqPmwHWut1m64zqsR20TXAJzr0xWL1SlJnyrGNT+ncKABZrz9ir4NTJH3qPc1oFduhlo7e0aT2ISfi1eTn2U6sf+8Qs5sCU0wB5sLbvafXkq/gEkHKJB9EplqtKSWinZkCNI81yPFolSO9AlhGIEwCa3jQWwHt2vLfLQhdCwOQkfboCZmqoaeEDEyGXxzlIebIJ0OmexsacpAFaYAoZGKAdSM+yfhBD3DWIujmFUCnBdoaRNbi29JhGJuaDfp2c9dXzbueO3dIRMDgh+l2jsvuCEoW2rbYnJRuPRr6akHU14lrtaQGkJaLmeW+BzeaA5Nd45WPG3p7wrHVUgjaOQoPSDe/aiq2Te0rz5sE4GJ7fJidsmE9kgNWi07vex8uJZQmzr2EH6+QuKg+BVQM+Ff0NUaTdxh4aAOv8EQhwFGgTqVYV+a2TiUMdP8u3MSs18d5kCHMLVCZeWI7/lGHCvWIiWxcqkIkAnz492l77w+cgJaocvzH+QIwRoL52josZI6GCPd5sw6fhSIQajJ2Z0VwEANBr28mi6sRujiTZSMZhrodMwTD6YEmvVoMSuXT7Y8ars0Utx0reMmLzCezPaUaWHtcMl9dApcBkArYJo8oze06BmiB5ZaoBJyS4SQ8yIQ==
  template:
    metadata:
      name: apple-health-db
      namespace: apple-health
