---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apple-health-db
  namespace: apple-health
spec:
  encryptedData:
    APPLE_HEALTH_DB_PASSWORD: AgDQBaLcNL1lmpWaus37FJF1Ju64SZc3GWnm5q0q5Z6etK8SPPvet0kXDykwQ02pdto70q+yWlI245MXF4oOHV8u3FxjXrckQCsAScFfFRHEgtSSGPFNhPHPayxeZ+klZW/pY5bA3Z75VeuA8QRHmupTff3y9FFfhHYXPGligjGPR1714++8Y3hViPSac60Eg6AySAeN7Yclj06qXkfdWpAz+fau40HUlHAEI5W9iDOQIOWHUQYuprxHSy6i3pW9zBpfX0Ekcl3pLQ6pHelB1q8KX42wy8KKh/SYOWEIjBMLQyNNmJ1rIKTmfVIy8s7u3rtuN5SwqNIbdYQr3Snh0Ij3WEAmY6a0BA6AfVQE9h6Q68PAqMRSSvbUEaYXGWfOiBtP5oyjqpQFNueghsL5QW+vEm06u2YEduprj5qV0wCWdrGEswD64DGSr7BLnTFRAQgXmQJaXr1Hn3VpDmHvAXzh1Tx5T8MoA5YEeoQ+R+aVw42IdLkfFOkacM1TI+09t14rs5lpKPW0gzqAZuy840AtYJw2hwwfKQ5pCzULs5vBXWIJC2tyYnatZFLlWndmrqJHeAmSTubje0BXj78cPd35RTZROR9Q0PBcICXHsyv5ZkNYPLM8FRW5i+nq4kbzeFdkRo7n4ftUqrqgQIw/Eg0lr0gkDstjpy4q5Q8YYpaXLBL3jRC5oIsGUWU/fLO5US3WkRRieEOSaDUIY/UuEXvU2fDU4x5DTBfnJEDGvJJIjw==
  template:
    metadata:
      name: apple-health-db
      namespace: apple-health
